GET https://walamin-server.onrender.com/users


###

POST  https://walamin-server.onrender.com/register
Content-Type: application/json

{
  "username": "Marsh",
  "password": "zahara",
  "token": "123456",
  "firstName": "Marsh",
  "lastName": "Mansur"
}


###

POST  https://walamin-server.onrender.com/login
Content-Type: application/json

{
  "username": "Marsh",
  "password": "zahara",
  "token": "123456",
  "firstName": "marsh",
  "lastName": "mansur"
}